### ISSUE TITLE
mech_client.interact.interact example not working

### ISSUE THREAD

**Issue by evangriffiths** [valory-xyz/mech-client#27]
If I try the simple example:
```
from mech_client.interact import ConfirmationType, interact

result = interact(
    prompt="Why is the sky blue?",
    confirmation_type=ConfirmationType.ON_CHAIN,
    agent_id=3,
    private_key_path="./private_key.txt",
    tool="prediction-online",
)
```

And execute it, I get an error:

```
% WEBSOCKET_ENDPOINT=wss://rpc.gnosischain.com/wss python example.py
Prompt uploaded: https://gateway.autonolas.tech/ipfs/f01701220df93b1063813298b990f21cd2bf8dfded593d7355ea75cd57423c62cd916ee84
Unable to estimate gas with default state , ContractCustomError: System.ArgumentException: Expected a positive number and got -16594444 (Parameter 'a')
   at Nethermind.JsonRpc.Modules.Eth.EthRpcModule.TxExecutor`1.ExecuteTx(TransactionForRpc transactionCall, BlockParameter blockParameter) in /_/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.TransactionExecutor.cs:line 39
   at InvokeStub_IEthRpcModule.eth_estimateGas(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
Error occured while sending the transaction: System.ArgumentException: Expected a positive number and got -16594444 (Parameter 'a')
   at Nethermind.JsonRpc.Modules.Eth.EthRpcModule.TxExecutor`1.ExecuteTx(TransactionForRpc transactionCall, BlockParameter blockParameter) in /_/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.TransactionExecutor.cs:line 39
   at InvokeStub_IEthRpcModule.eth_estimateGas(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture); Retrying in 3.0
```

**Comment by DavidMinarsch** [comment]
Fixed in https://github.com/valory-xyz/mech-client/releases/tag/v0.2.10
